### ISSUE TITLE
Conceal されたテキストが非表示になっていない

### ISSUE THREAD

**Issue by crazymaster** [vim-jp/vimdoc-ja-working#116]
http://vimhelp.appspot.com/
これ見ると、ちゃんとconcealされていたので気になりました。

おそらく最初から入っているのはvim-tinyのはずなので、-concealになっているせいだと思います。

**Comment by koron** [comment]
とすると、自前でVimをビルドするしかないのか…どこかで似たようなことやってた記憶が…

**Comment by crazymaster** [comment]
最新版が必要というわけではないのでこれで行けるかと...
```
addons:
  apt:
    packages:
      - vim
```
いつの間にかコンテナベースでtrusty使えるようになってた(まだBetaになっているけど)
